title: Vineet John 
description: |
    Graduate Researcher (NLP & Applied ML)
    Software Development Engineer
    [LinkedIn](https://www.linkedin.com/in/johnvineet/)

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
